# Project information
site_name: "Car Maintenance App"
docs_dir: docs  # Where to find the English markdown files
site_dir: site  # Where to put the English HTML files
site_author: 'Hikmethan KOLAY / Yağız Emre ÖZBİLGE'
site_url: 'https://hikmethankolay.github.io/ce103-final-hikmethan-kolay-yagizemre-ozbilge-csharp/'
site_description: >-
    .Net Core Project Template for CI/CD

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/hikmethankolay/ce103-final-hikmethan-kolay-yagizemre-ozbilge-csharp'
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019 - 2023 Uğur CORUH

theme:
  name: material
  
nav:
    - Introduction: 'index.md'
    - Developers: 'developers.md'
    - 'Doxygen': 'doxygen/html/index.html'
    - 'Test Coverage': 'coveragereport/index.html'
    - 'Doc Coverage': 'coverxygen/index.html'